/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
        import React, { useRef } from 'react'
        import { useGLTF, 
        
         } from '@react-three/drei'
        
        
        export default function Model(props) {
          const group = useRef()
          const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/desk/model.gltf')
          return (
            <group ref={group} {...props} dispose={null}>
        <group position={[-4.26, 31.74, -0.17,]} scale={1.43} >
<mesh geometry={nodes.Cube007.geometry} material={materials.MetalBlack} />
<mesh geometry={nodes.Cube007_1.geometry} material={materials.DeskWood} />
</group>

            </group>
          )
        }

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/desk/model.gltf')